-- =============================================================================
-- FinMart Star Schema — Build Script
-- =============================================================================
-- Architecture: Star schema with 3 conformed dimensions and 1 fact table.
-- Source:       raw_orders, raw_customers, raw_products (generated by
--               generate_data.py)
-- Output:       dim_date, dim_customer, dim_product, fct_orders
--
-- Execution order:
--   1. dim_date
--   2. dim_customer
--   3. dim_product
--   4. fct_orders
-- =============================================================================


-- -----------------------------------------------------------------------------
-- dim_date
-- Grain: one row per calendar date present in raw_orders.
-- Date key: integer in YYYYMMDD format. Avoids DATE type comparisons in join
-- conditions and is compatible with downstream tools expecting integer surrogate keys.
-- -----------------------------------------------------------------------------

CREATE OR REPLACE TABLE dim_date AS
SELECT DISTINCT
    CAST(STRFTIME(order_date, '%Y%m%d') AS INTEGER)         AS date_key,
    CAST(order_date AS DATE)                                AS date,
    EXTRACT(YEAR      FROM order_date)::INT                 AS year,
    EXTRACT(QUARTER   FROM order_date)::INT                 AS quarter,
    EXTRACT(MONTH     FROM order_date)::INT                 AS month,
    EXTRACT(DAY       FROM order_date)::INT                 AS day,
    EXTRACT(DAYOFWEEK FROM order_date)::INT                 AS day_of_week,
    CASE
        WHEN EXTRACT(DAYOFWEEK FROM order_date) IN (0, 6)
        THEN TRUE ELSE FALSE
    END                                                     AS is_weekend
FROM raw_orders;


-- -----------------------------------------------------------------------------
-- dim_customer
-- Grain: one row per customer (Type 0, no history).
-- Note: Project 3 extends dim_customer to SCD Type 2 to support
-- point-in-time reconstruction.
-- Surrogate key: customer_key generated via ROW_NUMBER(). Natural key
-- (customer_id) is retained as a business key for source system traceability
-- but is never used as a foreign key in fact tables.
-- -----------------------------------------------------------------------------

CREATE OR REPLACE TABLE dim_customer AS
SELECT
    ROW_NUMBER() OVER (ORDER BY customer_id)  AS customer_key,
    customer_id,
    region,
    country,
    segment
FROM raw_customers;


-- -----------------------------------------------------------------------------
-- dim_product
-- Grain: one row per product.
-- Surrogate key: product_key generated via ROW_NUMBER(). The natural key
-- (product_id) is retained for source system traceability.
-- cost_price is stored here for margin analysis. It is NOT used in
-- fct_orders to avoid embedding cost logic in the fact table grain.
-- -----------------------------------------------------------------------------

CREATE OR REPLACE TABLE dim_product AS
SELECT
    ROW_NUMBER() OVER (ORDER BY product_id)  AS product_key,
    product_id,
    product_name                              AS name,
    category,
    subcategory,
    cost_price
FROM raw_products;


-- -----------------------------------------------------------------------------
-- fct_orders
-- Grain: one row per order line item (order_id + product_id combination).
-- Foreign keys: date_key, customer_key, product_key reference surrogate keys
-- in dimension tables
-- Precomputed metrics: gross_revenue and net_revenue are calculated at load
-- time to ensure consistent definitions across all downstream queries.
-- Rejected alternative: storing revenue only as quantity * unit_price at
-- query time. Rejected because ad-hoc recalculation produces inconsistent
-- results when analysts apply different refund logic independently.
-- -----------------------------------------------------------------------------

CREATE OR REPLACE TABLE fct_orders AS
SELECT
    o.order_id,
    d.date_key,
    c.customer_key,
    p.product_key,
    o.quantity,
    o.unit_price,
    o.quantity * o.unit_price                                   AS gross_revenue,
    o.is_refunded,
    CASE WHEN o.is_refunded THEN 0
         ELSE o.quantity * o.unit_price
    END                                                         AS net_revenue
FROM raw_orders o
JOIN dim_date     d ON CAST(STRFTIME(o.order_date, '%Y%m%d') AS INTEGER) = d.date_key
JOIN dim_customer c ON o.customer_id  = c.customer_id
JOIN dim_product  p ON o.product_id   = p.product_id;

